{% set name = "geoPFA" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geopfa-{{ version }}.tar.gz
  sha256: afc9f507eb86bde793bcf40712ccbe2ca75f801941306a8db9d09916b1ed8472

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.9
    - hatch-vcs >=0.5
    - pip
  run:
    - python >={{ python_min }}
    - iapws >=1.5.4
    - matplotlib-base >=3.1
    - networkx >=2.3
    - notebook
    - numpy >=1.16
    - pandas >=2.0
    - psutil >=6.1.0
    - pytest >=5.2
    - pyarrow >=21.0.0,<22
    - pooch >=1.8.2,<2
    - seaborn >=0.13.2
    - geopandas >=1.0
    - rasterio >=1.4.2
    - nrel-rex >=0.2.42
    - shapely >=2.0.6
    - scipy >=1.11
    - contextily >=1.6.2
    - pathos >=0.3.3
    - pykrige >=1.7
    - geostatspy >=0.0.72,<0.0.73
    - gpy >=1.13.2

test:
  imports:
    - geoPFA
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/geoPFA/
  summary: Geothermal Play Fairway Analysis
  dev_url: https://github.com/NREL/geoPFA
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ntaverna
    - castelao
